# Generated by Django 5.1.2 on 2024-12-08 03:31

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directorgeneral',
            options={'ordering': ['id'], 'verbose_name': 'Director General', 'verbose_name_plural': 'Director General'},
        ),
        migrations.AlterModelOptions(
            name='laboratorio',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='producto',
            name='f_fabricacion',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2015, 1, 1))]),
        ),
    ]
